# Generated by Django 4.1.7 on 2023-03-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='udpated',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='udpated',
            new_name='updated',
        ),
    ]
